//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.530
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetExtensions.Security.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SecurityResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SecurityResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetExtensions.Security.Resources.SecurityResources", typeof(SecurityResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionString not specified..
        /// </summary>
        internal static string MessageAdamConnectionStringNotSpecified {
            get {
                return ResourceManager.GetString("MessageAdamConnectionStringNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error converting SID to string: {0}..
        /// </summary>
        internal static string MessageAdamSIDConvertionFailed {
            get {
                return ResourceManager.GetString("MessageAdamSIDConvertionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is disabled..
        /// </summary>
        internal static string MessageAppServiceDisabled {
            get {
                return ResourceManager.GetString("MessageAppServiceDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccessCheck failed..
        /// </summary>
        internal static string MessageAzManAccessCheckFailed {
            get {
                return ResourceManager.GetString("MessageAzManAccessCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occured..
        /// </summary>
        internal static string MessageAzManAnExceptionOccured {
            get {
                return ResourceManager.GetString("MessageAzManAnExceptionOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AzMan application name not specified..
        /// </summary>
        internal static string MessageAzManApplicationNameNotSpecified {
            get {
                return ResourceManager.GetString("MessageAzManApplicationNameNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionString not specified..
        /// </summary>
        internal static string MessageAzManConnectionStringNotSpecified {
            get {
                return ResourceManager.GetString("MessageAzManConnectionStringNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AzMan GetOperations failed..
        /// </summary>
        internal static string MessageAzManGetOperationsFailed {
            get {
                return ResourceManager.GetString("MessageAzManGetOperationsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize AzManHelper..
        /// </summary>
        internal static string MessageAzManHelperInitializeFailed {
            get {
                return ResourceManager.GetString("MessageAzManHelperInitializeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load Azman Role Policy: invalid ConnectionString {0}..
        /// </summary>
        internal static string MessageAzManInvalidConnectionString {
            get {
                return ResourceManager.GetString("MessageAzManInvalidConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be empty..
        /// </summary>
        internal static string MessageAzManParameterArrayCannotBeEmpty {
            get {
                return ResourceManager.GetString("MessageAzManParameterArrayCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot contain duplicates..
        /// </summary>
        internal static string MessageAzManParameterArrayCannotContainDuplicates {
            get {
                return ResourceManager.GetString("MessageAzManParameterArrayCannotContainDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot contain commas..
        /// </summary>
        internal static string MessageAzManParameterCannotContainCommas {
            get {
                return ResourceManager.GetString("MessageAzManParameterCannotContainCommas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be empty..
        /// </summary>
        internal static string MessageAzManParameterIsEmpty {
            get {
                return ResourceManager.GetString("MessageAzManParameterIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot exceed {1} characters..
        /// </summary>
        internal static string MessageAzManParameterTooLong {
            get {
                return ResourceManager.GetString("MessageAzManParameterTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} role already exists..
        /// </summary>
        internal static string MessageAzManRoleAlreadyExists {
            get {
                return ResourceManager.GetString("MessageAzManRoleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} role does not exist..
        /// </summary>
        internal static string MessageAzManRoleDoesNotExist {
            get {
                return ResourceManager.GetString("MessageAzManRoleDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} role is not empty..
        /// </summary>
        internal static string MessageAzManRoleIsNotEmpty {
            get {
                return ResourceManager.GetString("MessageAzManRoleIsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update AzMan cache failed.
        /// </summary>
        internal static string MessageAzManUpdateCacheFailed {
            get {
                return ResourceManager.GetString("MessageAzManUpdateCacheFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} user does not exist.
        /// </summary>
        internal static string MessageAzManUserDoesNotExist {
            get {
                return ResourceManager.GetString("MessageAzManUserDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access is denied. Security principal should be a AmxPrincipal type..
        /// </summary>
        internal static string MessagePermissionAccessDeniedInvalidPrincipal {
            get {
                return ResourceManager.GetString("MessagePermissionAccessDeniedInvalidPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access is denied. Security principal does not satisfy required operations..
        /// </summary>
        internal static string MessagePermissionAccessDeniedUserCannotAccess {
            get {
                return ResourceManager.GetString("MessagePermissionAccessDeniedUserCannotAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access is denied. Security principal is not authenticated..
        /// </summary>
        internal static string MessagePermissionAccessDeniedUserNotAuthenticated {
            get {
                return ResourceManager.GetString("MessagePermissionAccessDeniedUserNotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Identity found..
        /// </summary>
        internal static string MessagePolicyNoIdentityFound {
            get {
                return ResourceManager.GetString("MessagePolicyNoIdentityFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoleProvider not found..
        /// </summary>
        internal static string MessageRoleProviderNotFound {
            get {
                return ResourceManager.GetString("MessageRoleProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles feature not enabled..
        /// </summary>
        internal static string MessageRolesFeatureNotEnabled {
            get {
                return ResourceManager.GetString("MessageRolesFeatureNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception occured. Please check with your administrator..
        /// </summary>
        internal static string MessageUnhandledException {
            get {
                return ResourceManager.GetString("MessageUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User is not authenticated..
        /// </summary>
        internal static string MessageUserIsNotAuthenticated {
            get {
                return ResourceManager.GetString("MessageUserIsNotAuthenticated", resourceCulture);
            }
        }
    }
}
